<?php

use Illuminate\Database\Seeder;

class DataTypesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_types')->delete();
        
        \DB::table('data_types')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'posts',
                'slug' => 'posts',
                'display_name_singular' => 'Notícia',
                'display_name_plural' => 'Notícias',
                'icon' => 'voyager-news',
                'model_name' => 'TCG\\Voyager\\Models\\Post',
                'policy_name' => 'TCG\\Voyager\\Policies\\PostPolicy',
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'created_at' => '2017-12-20 12:07:03',
                'updated_at' => '2017-12-20 12:07:03',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'pages',
                'slug' => 'pages',
                'display_name_singular' => 'Página',
                'display_name_plural' => 'Páginas',
                'icon' => 'voyager-file-text',
                'model_name' => 'App\\Models\\Page',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'created_at' => '2017-12-20 12:07:03',
                'updated_at' => '2017-12-23 16:38:52',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'users',
                'slug' => 'users',
                'display_name_singular' => 'Usuário',
                'display_name_plural' => 'Usuários',
                'icon' => 'voyager-person',
                'model_name' => 'TCG\\Voyager\\Models\\User',
                'policy_name' => 'TCG\\Voyager\\Policies\\UserPolicy',
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'created_at' => '2017-12-20 12:07:03',
                'updated_at' => '2017-12-20 12:07:03',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'categories',
                'slug' => 'categories',
                'display_name_singular' => 'Categoria',
                'display_name_plural' => 'Categorias',
                'icon' => 'voyager-categories',
                'model_name' => 'TCG\\Voyager\\Models\\Category',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'created_at' => '2017-12-20 12:07:03',
                'updated_at' => '2017-12-20 12:07:03',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'menus',
                'slug' => 'menus',
                'display_name_singular' => 'Menu',
                'display_name_plural' => 'Menus',
                'icon' => 'voyager-list',
                'model_name' => 'TCG\\Voyager\\Models\\Menu',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'created_at' => '2017-12-20 12:07:03',
                'updated_at' => '2017-12-20 12:07:03',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'roles',
                'slug' => 'roles',
                'display_name_singular' => 'Role',
                'display_name_plural' => 'Roles',
                'icon' => 'voyager-lock',
                'model_name' => 'TCG\\Voyager\\Models\\Role',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'created_at' => '2017-12-20 12:07:03',
                'updated_at' => '2017-12-20 12:07:03',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'slides',
                'slug' => 'slides',
                'display_name_singular' => 'Slide',
                'display_name_plural' => 'Slides',
                'icon' => 'voyager-images',
                'model_name' => 'App\\Models\\Slide',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'created_at' => '2017-12-20 12:07:03',
                'updated_at' => '2017-12-20 12:07:03',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'slide_images',
                'slug' => 'slide_images',
                'display_name_singular' => 'Imagem do Slide',
                'display_name_plural' => 'Imagens do Slide',
                'icon' => 'voyager-images',
                'model_name' => 'App\\Models\\SlideImage',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'created_at' => '2017-12-20 12:07:03',
                'updated_at' => '2017-12-20 12:07:03',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'galleries',
                'slug' => 'galleries',
                'display_name_singular' => 'Galeria',
                'display_name_plural' => 'Galerias',
                'icon' => 'voyager-images',
                'model_name' => 'App\\Models\\Gallery',
                'policy_name' => NULL,
                'controller' => 'Admin\\GalleryController',
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'created_at' => '2017-12-20 12:07:03',
                'updated_at' => '2017-12-21 17:00:23',
            ),
            9 => 
            array (
                'id' => 11,
                'name' => 'contacts',
                'slug' => 'contacts',
                'display_name_singular' => 'Contato',
                'display_name_plural' => 'Contatos',
                'icon' => 'voyager-chat',
                'model_name' => 'App\\Models\\Contact',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'created_at' => '2017-12-20 12:23:33',
                'updated_at' => '2017-12-20 12:35:28',
            ),
            10 => 
            array (
                'id' => 13,
                'name' => 'subjects',
                'slug' => 'subjects',
                'display_name_singular' => 'Assunto',
                'display_name_plural' => 'Assuntos',
                'icon' => 'voyager-question',
                'model_name' => 'App\\Models\\Subject',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'created_at' => '2017-12-20 14:05:23',
                'updated_at' => '2017-12-20 14:05:23',
            ),
            11 => 
            array (
                'id' => 14,
                'name' => 'newsletters',
                'slug' => 'newsletters',
                'display_name_singular' => 'Newsletter',
                'display_name_plural' => 'Newsletters',
                'icon' => NULL,
                'model_name' => 'App\\Models\\Newsletter',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'created_at' => '2017-12-20 15:06:02',
                'updated_at' => '2017-12-22 10:46:10',
            ),
            12 => 
            array (
                'id' => 16,
                'name' => 'positions',
                'slug' => 'positions',
                'display_name_singular' => 'Posição',
                'display_name_plural' => 'Posições',
                'icon' => 'voyager-crop',
                'model_name' => 'App\\Models\\Position',
                'policy_name' => NULL,
                'controller' => 'Admin\\PositionController',
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'created_at' => '2017-12-20 18:05:44',
                'updated_at' => '2017-12-20 18:28:25',
            ),
            13 => 
            array (
                'id' => 17,
                'name' => 'highlights',
                'slug' => 'highlights',
                'display_name_singular' => 'Highlight',
                'display_name_plural' => 'Highlights',
                'icon' => NULL,
                'model_name' => 'App\\Models\\Highlight',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'created_at' => '2017-12-20 18:00:06',
                'updated_at' => '2017-12-20 18:00:06',
            ),
            14 => 
            array (
                'id' => 18,
                'name' => 'services',
                'slug' => 'services',
                'display_name_singular' => 'Serviço',
                'display_name_plural' => 'Serviços',
                'icon' => NULL,
                'model_name' => 'App\\Models\\Service',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'created_at' => '2017-12-23 17:04:09',
                'updated_at' => '2017-12-23 17:04:09',
            ),
            15 => 
            array (
                'id' => 19,
                'name' => 'accordions',
                'slug' => 'accordions',
                'display_name_singular' => 'Accordion',
                'display_name_plural' => 'Accordions',
                'icon' => 'voyager-list',
                'model_name' => 'App\\Models\\Accordion',
                'policy_name' => NULL,
                'controller' => 'Admin\\AccordionController',
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'created_at' => '2017-12-23 17:59:29',
                'updated_at' => '2017-12-23 18:03:06',
            ),
            16 => 
            array (
                'id' => 22,
                'name' => 'reports',
                'slug' => 'boletins',
                'display_name_singular' => 'Boletim',
                'display_name_plural' => 'Boletins',
                'icon' => NULL,
                'model_name' => 'App\\Models\\Report',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'created_at' => '2018-01-03 12:10:01',
                'updated_at' => '2018-01-03 12:10:01',
            ),
            17 => 
            array (
                'id' => 24,
                'name' => 'newsletter_categories',
                'slug' => 'newsletter-categories',
                'display_name_singular' => 'Categoria de Newsletter',
                'display_name_plural' => 'Categorias de Newsletter',
                'icon' => NULL,
                'model_name' => 'App\\Models\\NewsletterCategory',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'created_at' => '2018-01-03 15:08:16',
                'updated_at' => '2018-01-03 15:08:16',
            ),
        ));
        
        
    }
}