<?php

use Illuminate\Database\Seeder;

class DataRowsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_rows')->delete();
        
        \DB::table('data_rows')->insert(array (
            0 => 
            array (
                'id' => 1,
                'data_type_id' => 1,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'data_type_id' => 1,
                'field' => 'author_id',
                'type' => 'text',
                'display_name' => 'Autor',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '',
                'order' => 2,
            ),
            2 => 
            array (
                'id' => 3,
                'data_type_id' => 1,
                'field' => 'category_id',
                'type' => 'text',
                'display_name' => 'Categoria',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '',
                'order' => 3,
            ),
            3 => 
            array (
                'id' => 4,
                'data_type_id' => 1,
                'field' => 'title',
                'type' => 'text',
                'display_name' => 'Título',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 7,
            ),
            4 => 
            array (
                'id' => 5,
                'data_type_id' => 1,
                'field' => 'excerpt',
                'type' => 'text_area',
                'display_name' => 'Resumo',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 5,
            ),
            5 => 
            array (
                'id' => 6,
                'data_type_id' => 1,
                'field' => 'body',
                'type' => 'rich_text_box',
                'display_name' => 'Conteúdo',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 6,
            ),
            6 => 
            array (
                'id' => 7,
                'data_type_id' => 1,
                'field' => 'image',
                'type' => 'image',
                'display_name' => 'Imagem',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"resize":{"width":"1000","height":"null"},"quality":"70%","upsize":true,"thumbnails":[{"name":"medium","scale":"50%"},{"name":"small","scale":"25%"},{"name":"cropped","crop":{"width":"300","height":"250"}}]}',
                'order' => 1,
            ),
            7 => 
            array (
                'id' => 8,
                'data_type_id' => 1,
                'field' => 'slug',
                'type' => 'text',
                'display_name' => 'Slug',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"slugify":{"origin":"title","forceUpdate":true}}',
                'order' => 8,
            ),
            8 => 
            array (
                'id' => 9,
                'data_type_id' => 1,
                'field' => 'seo_title',
                'type' => 'text',
            'display_name' => 'Título (SEO)',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 14,
            ),
            9 => 
            array (
                'id' => 10,
                'data_type_id' => 1,
                'field' => 'meta_description',
                'type' => 'text_area',
                'display_name' => 'Meta Description',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 9,
            ),
            10 => 
            array (
                'id' => 11,
                'data_type_id' => 1,
                'field' => 'meta_keywords',
                'type' => 'text_area',
                'display_name' => 'Meta Keywords',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 10,
            ),
            11 => 
            array (
                'id' => 12,
                'data_type_id' => 1,
                'field' => 'status',
                'type' => 'select_dropdown',
                'display_name' => 'Status',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"default":"DRAFT","options":{"PUBLISHED":"Publicado","DRAFT":"Rascunho","PENDING":"Pendente"}}',
                'order' => 11,
            ),
            12 => 
            array (
                'id' => 13,
                'data_type_id' => 1,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criado em',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 12,
            ),
            13 => 
            array (
                'id' => 14,
                'data_type_id' => 1,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Atualizado em',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 13,
            ),
            14 => 
            array (
                'id' => 15,
                'data_type_id' => 1,
                'field' => 'featured',
                'type' => 'checkbox',
                'display_name' => 'Destaque',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 15,
            ),
            15 => 
            array (
                'id' => 16,
                'data_type_id' => 2,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 5,
            ),
            16 => 
            array (
                'id' => 17,
                'data_type_id' => 2,
                'field' => 'author_id',
                'type' => 'text',
                'display_name' => 'Autor',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 6,
            ),
            17 => 
            array (
                'id' => 18,
                'data_type_id' => 2,
                'field' => 'title',
                'type' => 'text',
                'display_name' => 'Título',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            18 => 
            array (
                'id' => 19,
                'data_type_id' => 2,
                'field' => 'excerpt',
                'type' => 'text_area',
                'display_name' => 'Resumo',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 7,
            ),
            19 => 
            array (
                'id' => 20,
                'data_type_id' => 2,
                'field' => 'body',
                'type' => 'rich_text_box',
                'display_name' => 'Conteúdo',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 8,
            ),
            20 => 
            array (
                'id' => 21,
                'data_type_id' => 2,
                'field' => 'image',
                'type' => 'image',
                'display_name' => 'Imagem',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 1,
            ),
            21 => 
            array (
                'id' => 22,
                'data_type_id' => 2,
                'field' => 'slug',
                'type' => 'text',
                'display_name' => 'Slug',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"slugify":{"origin":"title","forceUpdate":true}}',
                'order' => 9,
            ),
            22 => 
            array (
                'id' => 23,
                'data_type_id' => 2,
                'field' => 'seo_title',
                'type' => 'text',
            'display_name' => 'Título (SEO)',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 11,
            ),
            23 => 
            array (
                'id' => 24,
                'data_type_id' => 2,
                'field' => 'meta_description',
                'type' => 'text',
                'display_name' => 'Meta Description',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 12,
            ),
            24 => 
            array (
                'id' => 25,
                'data_type_id' => 2,
                'field' => 'meta_keywords',
                'type' => 'text',
                'display_name' => 'Meta Keywords',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 13,
            ),
            25 => 
            array (
                'id' => 26,
                'data_type_id' => 2,
                'field' => 'status',
                'type' => 'select_dropdown',
                'display_name' => 'Status',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"default":"DRAFT","options":{"PUBLISHED":"Publicado","DRAFT":"Rascunho","PENDING":"Pendente"}}',
                'order' => 3,
            ),
            26 => 
            array (
                'id' => 27,
                'data_type_id' => 2,
                'field' => 'exibir_menu',
                'type' => 'checkbox',
                'display_name' => 'Exibir no menu',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 10,
            ),
            27 => 
            array (
                'id' => 28,
                'data_type_id' => 2,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criado em',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            28 => 
            array (
                'id' => 29,
                'data_type_id' => 2,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Atualizado em',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 14,
            ),
            29 => 
            array (
                'id' => 30,
                'data_type_id' => 3,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 1,
            ),
            30 => 
            array (
                'id' => 31,
                'data_type_id' => 3,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 2,
            ),
            31 => 
            array (
                'id' => 32,
                'data_type_id' => 3,
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'email',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 3,
            ),
            32 => 
            array (
                'id' => 33,
                'data_type_id' => 3,
                'field' => 'password',
                'type' => 'password',
                'display_name' => 'password',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '',
                'order' => 4,
            ),
            33 => 
            array (
                'id' => 34,
                'data_type_id' => 3,
                'field' => 'user_belongsto_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Role',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"name","pivot_table":"roles","pivot":"0"}',
                'order' => 10,
            ),
            34 => 
            array (
                'id' => 35,
                'data_type_id' => 3,
                'field' => 'remember_token',
                'type' => 'text',
                'display_name' => 'remember_token',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 5,
            ),
            35 => 
            array (
                'id' => 36,
                'data_type_id' => 3,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'created_at',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 6,
            ),
            36 => 
            array (
                'id' => 37,
                'data_type_id' => 3,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'updated_at',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 7,
            ),
            37 => 
            array (
                'id' => 38,
                'data_type_id' => 3,
                'field' => 'avatar',
                'type' => 'image',
                'display_name' => 'avatar',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 8,
            ),
            38 => 
            array (
                'id' => 39,
                'data_type_id' => 5,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 1,
            ),
            39 => 
            array (
                'id' => 40,
                'data_type_id' => 5,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 2,
            ),
            40 => 
            array (
                'id' => 41,
                'data_type_id' => 5,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'created_at',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 3,
            ),
            41 => 
            array (
                'id' => 42,
                'data_type_id' => 5,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'updated_at',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 4,
            ),
            42 => 
            array (
                'id' => 43,
                'data_type_id' => 4,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 1,
            ),
            43 => 
            array (
                'id' => 44,
                'data_type_id' => 4,
                'field' => 'parent_id',
                'type' => 'select_dropdown',
                'display_name' => 'parent_id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"default":"","null":"","options":{"":"-- None --"},"relationship":{"key":"id","label":"name"}}',
                'order' => 2,
            ),
            44 => 
            array (
                'id' => 45,
                'data_type_id' => 4,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nome',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 4,
            ),
            45 => 
            array (
                'id' => 46,
                'data_type_id' => 4,
                'field' => 'slug',
                'type' => 'text',
                'display_name' => 'Slug',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"slugify":{"origin":"name"}}',
                'order' => 5,
            ),
            46 => 
            array (
                'id' => 47,
                'data_type_id' => 4,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'created_at',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 6,
            ),
            47 => 
            array (
                'id' => 48,
                'data_type_id' => 4,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'updated_at',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 7,
            ),
            48 => 
            array (
                'id' => 49,
                'data_type_id' => 6,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 1,
            ),
            49 => 
            array (
                'id' => 50,
                'data_type_id' => 6,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 2,
            ),
            50 => 
            array (
                'id' => 51,
                'data_type_id' => 6,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'created_at',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 3,
            ),
            51 => 
            array (
                'id' => 52,
                'data_type_id' => 6,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'updated_at',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 4,
            ),
            52 => 
            array (
                'id' => 53,
                'data_type_id' => 6,
                'field' => 'display_name',
                'type' => 'text',
                'display_name' => 'Display Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 5,
            ),
            53 => 
            array (
                'id' => 54,
                'data_type_id' => 3,
                'field' => 'role_id',
                'type' => 'text',
                'display_name' => 'role_id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 9,
            ),
            54 => 
            array (
                'id' => 55,
                'data_type_id' => 7,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 1,
            ),
            55 => 
            array (
                'id' => 56,
                'data_type_id' => 7,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nome',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 2,
            ),
            56 => 
            array (
                'id' => 57,
                'data_type_id' => 7,
                'field' => 'slug',
                'type' => 'text',
                'display_name' => 'Slug',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"slugify":{"origin":"title","forceUpdate":true}}',
                'order' => 3,
            ),
            57 => 
            array (
                'id' => 58,
                'data_type_id' => 7,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'created_at',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 4,
            ),
            58 => 
            array (
                'id' => 59,
                'data_type_id' => 7,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'updated_at',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 5,
            ),
            59 => 
            array (
                'id' => 60,
                'data_type_id' => 8,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 1,
            ),
            60 => 
            array (
                'id' => 61,
                'data_type_id' => 8,
                'field' => 'slide_id',
                'type' => 'text',
                'display_name' => 'Slide',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 4,
            ),
            61 => 
            array (
                'id' => 62,
                'data_type_id' => 8,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nome',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 3,
            ),
            62 => 
            array (
                'id' => 63,
                'data_type_id' => 8,
                'field' => 'image',
                'type' => 'image',
                'display_name' => 'Imagem',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"resize":{"width":"1000","height":"null"},"quality":"70%","upsize":true,"thumbnails":[{"name":"medium","scale":"50%"},{"name":"small","scale":"25%"},{"name":"cropped","crop":{"width":"300","height":"250"}}]}',
                'order' => 2,
            ),
            63 => 
            array (
                'id' => 64,
                'data_type_id' => 8,
                'field' => 'description',
                'type' => 'text',
                'display_name' => 'Descrição',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 5,
            ),
            64 => 
            array (
                'id' => 65,
                'data_type_id' => 8,
                'field' => 'link',
                'type' => 'text',
                'display_name' => 'Link',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 6,
            ),
            65 => 
            array (
                'id' => 66,
                'data_type_id' => 8,
                'field' => 'label_link',
                'type' => 'text',
                'display_name' => 'Label link',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 7,
            ),
            66 => 
            array (
                'id' => 67,
                'data_type_id' => 8,
                'field' => 'target',
                'type' => 'text',
                'display_name' => 'Target',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 8,
            ),
            67 => 
            array (
                'id' => 68,
                'data_type_id' => 8,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criado em',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 9,
            ),
            68 => 
            array (
                'id' => 69,
                'data_type_id' => 8,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Atualizado em',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 10,
            ),
            69 => 
            array (
                'id' => 80,
                'data_type_id' => 9,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            70 => 
            array (
                'id' => 81,
                'data_type_id' => 9,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nome',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            71 => 
            array (
                'id' => 82,
                'data_type_id' => 9,
                'field' => 'slug',
                'type' => 'text',
                'display_name' => 'Slug',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"slugify":{"origin":"name","forceUpdate":true}}',
                'order' => 3,
            ),
            72 => 
            array (
                'id' => 83,
                'data_type_id' => 9,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            73 => 
            array (
                'id' => 84,
                'data_type_id' => 9,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'updated_at',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 5,
            ),
            74 => 
            array (
                'id' => 85,
                'data_type_id' => 11,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            75 => 
            array (
                'id' => 86,
                'data_type_id' => 11,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nome',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 2,
            ),
            76 => 
            array (
                'id' => 87,
                'data_type_id' => 11,
                'field' => 'subject',
                'type' => 'text',
                'display_name' => 'Assunto',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 3,
            ),
            77 => 
            array (
                'id' => 88,
                'data_type_id' => 11,
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'Email',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"validation":{"rule":"email"}}',
                'order' => 4,
            ),
            78 => 
            array (
                'id' => 89,
                'data_type_id' => 11,
                'field' => 'phone',
                'type' => 'text',
                'display_name' => 'Telefone',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"display":{"class":"phone"}}',
                'order' => 5,
            ),
            79 => 
            array (
                'id' => 90,
                'data_type_id' => 11,
                'field' => 'cellphone',
                'type' => 'text',
                'display_name' => 'Celular',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"display":{"class":"phone"}}',
                'order' => 6,
            ),
            80 => 
            array (
                'id' => 91,
                'data_type_id' => 11,
                'field' => 'message',
                'type' => 'text_area',
                'display_name' => 'Mensagem',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 7,
            ),
            81 => 
            array (
                'id' => 92,
                'data_type_id' => 11,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criado em',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 8,
            ),
            82 => 
            array (
                'id' => 93,
                'data_type_id' => 11,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Atualizado em',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 9,
            ),
            83 => 
            array (
                'id' => 94,
                'data_type_id' => 13,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            84 => 
            array (
                'id' => 95,
                'data_type_id' => 13,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nome',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required","messages":{"required":"Campo obrigatório!"}}}',
                'order' => 2,
            ),
            85 => 
            array (
                'id' => 96,
                'data_type_id' => 13,
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'Email',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"email|nullable","messages":{"required":"Email inválido!"}}}',
                'order' => 3,
            ),
            86 => 
            array (
                'id' => 97,
                'data_type_id' => 13,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criado em',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            87 => 
            array (
                'id' => 98,
                'data_type_id' => 13,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Atualizado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 5,
            ),
            88 => 
            array (
                'id' => 99,
                'data_type_id' => 14,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            89 => 
            array (
                'id' => 100,
                'data_type_id' => 14,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nome',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            90 => 
            array (
                'id' => 101,
                'data_type_id' => 14,
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'Email',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"email"}}',
                'order' => 3,
            ),
            91 => 
            array (
                'id' => 102,
                'data_type_id' => 14,
                'field' => 'phone',
                'type' => 'text',
                'display_name' => 'Telefone',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 4,
            ),
            92 => 
            array (
                'id' => 103,
                'data_type_id' => 14,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 5,
            ),
            93 => 
            array (
                'id' => 104,
                'data_type_id' => 14,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Atualizado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 6,
            ),
            94 => 
            array (
                'id' => 105,
                'data_type_id' => 16,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            95 => 
            array (
                'id' => 106,
                'data_type_id' => 16,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nome',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            96 => 
            array (
                'id' => 107,
                'data_type_id' => 16,
                'field' => 'slug',
                'type' => 'text',
                'display_name' => 'Slug',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"slugify":{"origin":"name","forceUpdate":true}}',
                'order' => 3,
            ),
            97 => 
            array (
                'id' => 113,
                'data_type_id' => 16,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criada em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"format":"d/m/Y"}',
                'order' => 4,
            ),
            98 => 
            array (
                'id' => 114,
                'data_type_id' => 17,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            99 => 
            array (
                'id' => 115,
                'data_type_id' => 17,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nome',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            100 => 
            array (
                'id' => 116,
                'data_type_id' => 17,
                'field' => 'model',
                'type' => 'select_dropdown',
                'display_name' => 'Model',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"options":{"page":"Página","post":"Notícia","link":"Link"}}',
                'order' => 3,
            ),
            101 => 
            array (
                'id' => 117,
                'data_type_id' => 17,
                'field' => 'foreign_key',
                'type' => 'select_dropdown',
                'display_name' => 'Foreign Key',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 4,
            ),
            102 => 
            array (
                'id' => 118,
                'data_type_id' => 17,
                'field' => 'title',
                'type' => 'text',
                'display_name' => 'Título',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 5,
            ),
            103 => 
            array (
                'id' => 119,
                'data_type_id' => 17,
                'field' => 'summary',
                'type' => 'text_area',
                'display_name' => 'Resumo',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 6,
            ),
            104 => 
            array (
                'id' => 120,
                'data_type_id' => 17,
                'field' => 'link',
                'type' => 'text',
                'display_name' => 'Link',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 7,
            ),
            105 => 
            array (
                'id' => 121,
                'data_type_id' => 17,
                'field' => 'image',
                'type' => 'image',
                'display_name' => 'Image',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 8,
            ),
            106 => 
            array (
                'id' => 122,
                'data_type_id' => 17,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criado em',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 9,
            ),
            107 => 
            array (
                'id' => 123,
                'data_type_id' => 17,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Atualizado em',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 10,
            ),
            108 => 
            array (
                'id' => 130,
                'data_type_id' => 16,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 5,
            ),
            109 => 
            array (
                'id' => 131,
                'data_type_id' => 18,
                'field' => 'id',
                'type' => 'checkbox',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            110 => 
            array (
                'id' => 132,
                'data_type_id' => 18,
                'field' => 'image',
                'type' => 'image',
                'display_name' => 'Imagem',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            111 => 
            array (
                'id' => 133,
                'data_type_id' => 18,
                'field' => 'title',
                'type' => 'text',
                'display_name' => 'Título',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 3,
            ),
            112 => 
            array (
                'id' => 134,
                'data_type_id' => 18,
                'field' => 'description',
                'type' => 'text_area',
                'display_name' => 'Descrição',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 4,
            ),
            113 => 
            array (
                'id' => 135,
                'data_type_id' => 18,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criado em',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 5,
            ),
            114 => 
            array (
                'id' => 136,
                'data_type_id' => 18,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Atualizado em',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 6,
            ),
            115 => 
            array (
                'id' => 137,
                'data_type_id' => 19,
                'field' => 'id',
                'type' => 'checkbox',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            116 => 
            array (
                'id' => 138,
                'data_type_id' => 19,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nome',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            117 => 
            array (
                'id' => 139,
                'data_type_id' => 19,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criado em',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 3,
            ),
            118 => 
            array (
                'id' => 140,
                'data_type_id' => 19,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Atualizado em',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            119 => 
            array (
                'id' => 141,
                'data_type_id' => 22,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            120 => 
            array (
                'id' => 142,
                'data_type_id' => 22,
                'field' => 'file',
                'type' => 'file',
                'display_name' => 'Arquivo',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 3,
            ),
            121 => 
            array (
                'id' => 143,
                'data_type_id' => 22,
                'field' => 'title',
                'type' => 'text',
                'display_name' => 'Título',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            122 => 
            array (
                'id' => 144,
                'data_type_id' => 22,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criado em',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            123 => 
            array (
                'id' => 145,
                'data_type_id' => 22,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Atualizado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 5,
            ),
            124 => 
            array (
                'id' => 146,
                'data_type_id' => 24,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            125 => 
            array (
                'id' => 147,
                'data_type_id' => 24,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nome',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            126 => 
            array (
                'id' => 148,
                'data_type_id' => 24,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criado em',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 3,
            ),
            127 => 
            array (
                'id' => 149,
                'data_type_id' => 24,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Atualizado em',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            128 => 
            array (
                'id' => 150,
                'data_type_id' => 14,
                'field' => 'newsletter_hasone_newsletter_category_relationship',
                'type' => 'relationship',
                'display_name' => 'Categoria',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\NewsletterCategory","table":"newsletter_categories","type":"belongsTo","column":"newsletter_category_id","key":"id","label":"name","pivot_table":"accordion_items","pivot":"0"}',
                'order' => 7,
            ),
            129 => 
            array (
                'id' => 151,
                'data_type_id' => 14,
                'field' => 'newsletter_category_id',
                'type' => 'checkbox',
                'display_name' => 'Newsletter Category Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
        ));
        
        
    }
}