<?php

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Dashboard',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-boat',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2017-12-20 12:07:06',
                'updated_at' => '2017-12-20 12:07:06',
                'route' => 'voyager.dashboard',
                'parameters' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Páginas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-file-text',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2017-12-20 12:07:06',
                'updated_at' => '2017-12-20 12:07:06',
                'route' => 'voyager.pages.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Notícias',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-news',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2017-12-20 12:07:06',
                'updated_at' => '2017-12-21 17:40:16',
                'route' => NULL,
                'parameters' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Notícias',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-news',
                'color' => NULL,
                'parent_id' => 3,
                'order' => 1,
                'created_at' => '2017-12-20 12:07:06',
                'updated_at' => '2017-12-20 13:55:27',
                'route' => 'voyager.posts.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Categorias',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-categories',
                'color' => NULL,
                'parent_id' => 3,
                'order' => 2,
                'created_at' => '2017-12-20 12:07:06',
                'updated_at' => '2017-12-20 13:55:28',
                'route' => 'voyager.categories.index',
                'parameters' => NULL,
            ),
            5 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Gerenciar slides',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => 6,
                'order' => 1,
                'created_at' => '2017-12-20 12:07:06',
                'updated_at' => '2017-12-20 13:55:28',
                'route' => 'voyager.slides.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Gerenciar imagens',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => 6,
                'order' => 2,
                'created_at' => '2017-12-20 12:07:06',
                'updated_at' => '2017-12-20 13:55:28',
                'route' => 'voyager.slide_images.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Galerias',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2017-12-20 12:07:06',
                'updated_at' => '2017-12-21 17:40:31',
                'route' => 'voyager.galleries.index',
                'parameters' => 'null',
            ),
            8 => 
            array (
                'id' => 12,
                'menu_id' => 1,
                'title' => 'Usuários',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2017-12-20 12:07:06',
                'updated_at' => '2017-12-23 18:03:21',
                'route' => NULL,
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 13,
                'menu_id' => 1,
                'title' => 'Usuários',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => 12,
                'order' => 1,
                'created_at' => '2017-12-20 12:07:06',
                'updated_at' => '2017-12-20 13:55:28',
                'route' => 'voyager.users.index',
                'parameters' => NULL,
            ),
            10 => 
            array (
                'id' => 14,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => 12,
                'order' => 2,
                'created_at' => '2017-12-20 12:07:06',
                'updated_at' => '2017-12-20 13:55:28',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            11 => 
            array (
                'id' => 15,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 10,
                'created_at' => '2017-12-20 12:07:06',
                'updated_at' => '2017-12-23 18:03:21',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            12 => 
            array (
                'id' => 16,
                'menu_id' => 1,
                'title' => 'Configurações',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 11,
                'created_at' => '2017-12-20 12:07:06',
                'updated_at' => '2017-12-23 18:03:21',
                'route' => 'voyager.settings.index',
                'parameters' => NULL,
            ),
            13 => 
            array (
                'id' => 17,
                'menu_id' => 1,
                'title' => 'Tools',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 12,
                'created_at' => '2017-12-20 12:07:06',
                'updated_at' => '2017-12-23 18:03:21',
                'route' => NULL,
                'parameters' => NULL,
            ),
            14 => 
            array (
                'id' => 18,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 17,
                'order' => 1,
                'created_at' => '2017-12-20 12:07:06',
                'updated_at' => '2017-12-20 13:55:28',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            15 => 
            array (
                'id' => 19,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 17,
                'order' => 2,
                'created_at' => '2017-12-20 12:07:06',
                'updated_at' => '2017-12-20 13:55:28',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            16 => 
            array (
                'id' => 20,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '/admin/compass',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 17,
                'order' => 3,
                'created_at' => '2017-12-20 12:07:06',
                'updated_at' => '2017-12-20 13:55:28',
                'route' => NULL,
                'parameters' => NULL,
            ),
            17 => 
            array (
                'id' => 21,
                'menu_id' => 1,
                'title' => 'Hooks',
                'url' => '/admin/hooks',
                'target' => '_self',
                'icon_class' => 'voyager-hook',
                'color' => NULL,
                'parent_id' => 17,
                'order' => 4,
                'created_at' => '2017-12-20 12:07:07',
                'updated_at' => '2017-12-20 13:55:28',
                'route' => NULL,
                'parameters' => NULL,
            ),
            18 => 
            array (
                'id' => 22,
                'menu_id' => 1,
                'title' => 'Contatos',
                'url' => '/admin/contacts',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 23,
                'order' => 1,
                'created_at' => '2017-12-20 12:23:33',
                'updated_at' => '2017-12-20 13:57:42',
                'route' => NULL,
                'parameters' => '',
            ),
            19 => 
            array (
                'id' => 23,
                'menu_id' => 1,
                'title' => 'Formulários',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-chat',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2017-12-20 13:57:17',
                'updated_at' => '2017-12-23 18:03:21',
                'route' => NULL,
                'parameters' => '',
            ),
            20 => 
            array (
                'id' => 24,
                'menu_id' => 1,
                'title' => 'Assuntos',
                'url' => '/admin/subjects',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 23,
                'order' => 2,
                'created_at' => '2017-12-20 14:05:23',
                'updated_at' => '2017-12-20 14:14:39',
                'route' => NULL,
                'parameters' => '',
            ),
            21 => 
            array (
                'id' => 27,
                'menu_id' => 1,
                'title' => 'Posições',
                'url' => '/admin/positions',
                'target' => '_self',
                'icon_class' => 'voyager-crop',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2017-12-20 18:05:44',
                'updated_at' => '2017-12-21 17:40:31',
                'route' => NULL,
                'parameters' => '',
            ),
            22 => 
            array (
                'id' => 28,
                'menu_id' => 1,
                'title' => 'Highlights',
                'url' => '/admin/highlights',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 13,
                'created_at' => '2017-12-20 18:00:06',
                'updated_at' => '2017-12-23 18:03:21',
                'route' => NULL,
                'parameters' => NULL,
            ),
            23 => 
            array (
                'id' => 29,
                'menu_id' => 1,
                'title' => 'Newsletters',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 23,
                'order' => 3,
                'created_at' => '2017-12-22 16:30:00',
                'updated_at' => '2017-12-22 16:30:05',
                'route' => 'voyager.newsletters.index',
                'parameters' => NULL,
            ),
            24 => 
            array (
                'id' => 30,
                'menu_id' => 1,
                'title' => 'Serviços',
                'url' => '/admin/services',
                'target' => '_self',
                'icon_class' => 'voyager-harddrive',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2017-12-23 17:04:09',
                'updated_at' => '2017-12-23 17:22:03',
                'route' => NULL,
                'parameters' => '',
            ),
            25 => 
            array (
                'id' => 31,
                'menu_id' => 1,
                'title' => 'Accordions',
                'url' => '/admin/accordions',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2017-12-23 17:59:29',
                'updated_at' => '2017-12-23 18:03:21',
                'route' => NULL,
                'parameters' => '',
            ),
            26 => 
            array (
                'id' => 32,
                'menu_id' => 1,
                'title' => 'Boletins',
                'url' => '/admin/boletins',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 14,
                'created_at' => '2018-01-03 12:10:01',
                'updated_at' => '2018-01-03 12:10:01',
                'route' => NULL,
                'parameters' => NULL,
            ),
            27 => 
            array (
                'id' => 33,
                'menu_id' => 1,
                'title' => 'Categorias de Newsletter',
                'url' => '/admin/newsletter-categories',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 15,
                'created_at' => '2018-01-03 15:08:17',
                'updated_at' => '2018-01-03 15:08:17',
                'route' => NULL,
                'parameters' => NULL,
            ),
        ));
        
        
    }
}